language: node_js
node_js:
  - "10"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - npm install -g --silent @angular/cli@9.1.9

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test:ci
  - npm run build-storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./storybook-static/

